const simpleMovies = [
    '3 Idiots',
    'Dangal',
    'PK',
    'Lagaan',
    'Gully Boy',
    'Kabir Singh',
    'Bahubali: The Beginning',
    'Bahubali: The Conclusion',
    'Dilwale Dulhania Le Jayenge',
    'Chennai Express',
    'Kuch Kuch Hota Hai',
    'Zindagi Na Milegi Dobara',
    'Barfi!',
    'Swades'
];


const movies = [
    {
        ID: 1,
        Title: '3 Idiots',
        Director: 'Rajkumar Hirani',
        Release_Year: 2009,
        Genre: 'Comedy-Drama',
        Rating: 8.4,
        PosterSrc: 'https://upload.wikimedia.org/wikipedia/en/d/df/3_idiots_poster.jpg',
    },
    {
        ID: 2,
        Title: 'Dangal',
        Director: 'Nitesh Tiwari',
        Release_Year: 2016,
        Genre: 'Biography',
        Rating: 8.4,
        PosterSrc: 'https://upload.wikimedia.org/wikipedia/en/9/99/Dangal_Poster.jpg',
    },
    {
        ID: 3,
        Title: 'PK',
        Director: 'Rajkumar Hirani',
        Release_Year: 2014,
        Genre: 'Comedy-Drama',
        Rating: 8.1,
        PosterSrc: 'https://upload.wikimedia.org/wikipedia/en/c/c3/PK_poster.jpg',
    },
    {
        ID: 4,
        Title: 'Lagaan',
        Director: 'Ashutosh Gowariker',
        Release_Year: 2001,
        Genre: 'Sport-Drama',
        Rating: 8.1,
        PosterSrc: 'https://upload.wikimedia.org/wikipedia/en/b/b6/Lagaan.jpg',
    },
    {
        ID: 5,
        Title: 'Gully Boy',
        Director: 'Zoya Akhtar',
        Release_Year: 2019,
        Genre: 'Musical-Drama',
        Rating: 8.0,
        PosterSrc: 'https://upload.wikimedia.org/wikipedia/en/9/9a/Gully_Boy_poster.jpg',
    },
    {
        ID: 6,
        Title: 'Kabir Singh',
        Director: 'Sandeep Reddy Vanga',
        Release_Year: 2019,
        Genre: 'Romantic-Drama',
        Rating: 7.1,
        PosterSrc: 'https://upload.wikimedia.org/wikipedia/en/7/7f/Kabir_Singh.jpg',
    },
    {
        ID: 7,
        Title: 'Bahubali: The Beginning',
        Director: 'S. S. Rajamouli',
        Release_Year: 2015,
        Genre: 'Action-Fantasy',
        Rating: 8.0,
        PosterSrc: 'https://upload.wikimedia.org/wikipedia/en/7/7e/Baahubali_the_Conclusion.jpg',
    },
    {
        ID: 8,
        Title: 'Bahubali: The Conclusion',
        Director: 'S. S. Rajamouli',
        Release_Year: 2017,
        Genre: 'Action-Fantasy',
        Rating: 8.2,
        PosterSrc: 'https://upload.wikimedia.org/wikipedia/en/f/f9/Baahubali_the_Beginning.jpg',
    },
    {
        ID: 9,
        Title: 'Dilwale Dulhania Le Jayenge',
        Director: 'Aditya Chopra',
        Release_Year: 1995,
        Genre: 'Romantic-Drama',
        Rating: 8.0,
        PosterSrc: 'https://upload.wikimedia.org/wikipedia/en/8/80/Dilwale_Dulhania_Le_Jayenge_poster.jpg',
    },
    {
        ID: 10,
        Title: 'Chennai Express',
        Director: 'Rohit Shetty',
        Release_Year: 2013,
        Genre: 'Action-Comedy',
        Rating: 6.0,
        PosterSrc: 'https://upload.wikimedia.org/wikipedia/en/2/2e/Chennai_Express.jpg',
    },
    {
        ID: 11,
        Title: 'Kuch Kuch Hota Hai',
        Director: 'Karan Johar',
        Release_Year: 1998,
        Genre: 'Romantic-Drama',
        Rating: 7.6,
        PosterSrc: 'https://upload.wikimedia.org/wikipedia/en/2/2d/Kuch_Kuch_Hota_Hai.jpg',
    },
    {
        ID: 12,
        Title: 'Zindagi Na Milegi Dobara',
        Director: 'Zoya Akhtar',
        Release_Year: 2011,
        Genre: 'Drama',
        Rating: 8.1,
        PosterSrc: 'https://upload.wikimedia.org/wikipedia/en/3/3e/Zindaginamilegidobara.jpg',
    },
    {
        ID: 13,
        Title: 'Barfi!',
        Director: 'Anurag Basu',
        Release_Year: 2012,
        Genre: 'Comedy-Drama',
        Rating: 8.1,
        PosterSrc: 'https://upload.wikimedia.org/wikipedia/en/9/95/Barfi%21_poster.jpg',
    },
    {
        ID: 14,
        Title: 'Swades',
        Director: 'Ashutosh Gowariker',
        Release_Year: 2004,
        Genre: 'Drama',
        Rating: 8.2,
        PosterSrc: 'https://upload.wikimedia.org/wikipedia/en/1/1e/Swades_poster.jpg',
    },
];
