const simpleMovies = [
    '3 Idiots',
    'Dangal',
    'PK',
    'Lagaan',
    'Gully Boy',
    'Kabir Singh',
    'Bahubali: The Beginning',
    'Bahubali: The Conclusion',
    'Dilwale Dulhania Le Jayenge',
    'Chennai Express',
    'Kuch Kuch Hota Hai',
    'Zindagi Na Milegi Dobara',
    'Barfi!',
    'Swades'
];


const movies = [
    {
        ID: 1,
        Title: '3 Idiots',
        Director: 'Rajkumar Hirani',
        Release_Year: 2009,
        Genre: 'Comedy-Drama',
        Rating: 8.4,
        PosterSrc: 'images/movies/3_idiots.jpg',
    },
    {
        ID: 2,
        Title: 'Dangal',
        Director: 'Nitesh Tiwari',
        Release_Year: 2016,
        Genre: 'Biography',
        Rating: 8.4,
        PosterSrc: 'images/movies/dangal.jpg',
    },
    {
        ID: 3,
        Title: 'PK',
        Director: 'Rajkumar Hirani',
        Release_Year: 2014,
        Genre: 'Comedy-Drama',
        Rating: 8.1,
        PosterSrc: 'images/movies/pk.jpg',
    },
    {
        ID: 4,
        Title: 'Lagaan',
        Director: 'Ashutosh Gowariker',
        Release_Year: 2001,
        Genre: 'Sport-Drama',
        Rating: 8.1,
        PosterSrc: 'images/movies/lagaan.jpg',
    },
    {
        ID: 5,
        Title: 'Gully Boy',
        Director: 'Zoya Akhtar',
        Release_Year: 2019,
        Genre: 'Musical-Drama',
        Rating: 8.0,
        PosterSrc: 'images/movies/gully_boy.jpg',
    },
    {
        ID: 6,
        Title: 'Kabir Singh',
        Director: 'Sandeep Reddy Vanga',
        Release_Year: 2019,
        Genre: 'Romantic-Drama',
        Rating: 7.1,
        PosterSrc: 'images/movies/kabir_singh.jpg',
    },
    {
        ID: 7,
        Title: 'Bahubali: The Beginning',
        Director: 'S. S. Rajamouli',
        Release_Year: 2015,
        Genre: 'Action-Fantasy',
        Rating: 8.0,
        PosterSrc: 'images/movies/bahubali_beginning.jpg',
    },
    {
        ID: 8,
        Title: 'Bahubali: The Conclusion',
        Director: 'S. S. Rajamouli',
        Release_Year: 2017,
        Genre: 'Action-Fantasy',
        Rating: 8.2,
        PosterSrc: 'images/movies/bahubali_conclusion.jpg',
    },
    {
        ID: 9,
        Title: 'Dilwale Dulhania Le Jayenge',
        Director: 'Aditya Chopra',
        Release_Year: 1995,
        Genre: 'Romantic-Drama',
        Rating: 8.0,
        PosterSrc: 'images/movies/ddlj.jpg',
    },
    {
        ID: 10,
        Title: 'Chennai Express',
        Director: 'Rohit Shetty',
        Release_Year: 2013,
        Genre: 'Action-Comedy',
        Rating: 6.0,
        PosterSrc: 'images/movies/chennai_express.jpg',
    },
    {
        ID: 11,
        Title: 'Kuch Kuch Hota Hai',
        Director: 'Karan Johar',
        Release_Year: 1998,
        Genre: 'Romantic-Drama',
        Rating: 7.6,
        PosterSrc: 'images/movies/kuch_kuch_hota_hai.jpg',
    },
    {
        ID: 12,
        Title: 'Zindagi Na Milegi Dobara',
        Director: 'Zoya Akhtar',
        Release_Year: 2011,
        Genre: 'Drama',
        Rating: 8.1,
        PosterSrc: 'images/movies/znmd.jpg',
    },
    {
        ID: 13,
        Title: 'Barfi!',
        Director: 'Anurag Basu',
        Release_Year: 2012,
        Genre: 'Comedy-Drama',
        Rating: 8.1,
        PosterSrc: 'images/movies/barfi.jpg',
    },
    {
        ID: 14,
        Title: 'Swades',
        Director: 'Ashutosh Gowariker',
        Release_Year: 2004,
        Genre: 'Drama',
        Rating: 8.2,
        PosterSrc: 'images/movies/swades.jpg',
    },
];
